// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRecord(arg1:string,arg2:string):Promise<void>;

export function DeleteById(arg1:string):Promise<void>;

export function GenUUID():Promise<string>;

export function GetAllRecords():Promise<string>;
