// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRecord(arg1, arg2) {
  return window['go']['main']['App']['CreateRecord'](arg1, arg2);
}

export function DeleteById(arg1) {
  return window['go']['main']['App']['DeleteById'](arg1);
}

export function GenUUID() {
  return window['go']['main']['App']['GenUUID']();
}

export function GetAllRecords() {
  return window['go']['main']['App']['GetAllRecords']();
}
